### ISSUE TITLE
Automatic reloading upon file changes

### ISSUE THREAD

**Issue by johannes-titz** [tomas/pixelhopper#1]
Fantastic job!

Is it feasible to implement an auto-reload feature for the file whenever changes occur? This would significantly streamline my workflow as I continuously regenerate a GIF until it meets my requirements.

**Comment by tomas** [comment]
I don't see why not, except maybe that I'd like the app to remain as light as possible...

Have you tried using the watch command or maybe inotifywait? You can find a few examples [here](https://stackoverflow.com/questions/12264238/restart-process-on-file-change-in-linux).

By the way, might I ask how you found out about Pixelhopper? I have barely mentioned in online!

**Comment by johannes-titz** [comment]
Oh, that's a new discovery for me! I wasn't aware that `watch` works for non-shell programs—pretty cool. I'm delighted with the simplicity of "Do one thing and do it well!"

I recently stumbled upon asciinema and agg for generating gifs of the casts. The main drawback I've encountered with gifs is their lack of scroll control and playback management. In my search, I discovered pixelhopper, which offers a neat solution. It's really cool!

So you can close this, I guess.

**Comment by tomas** [comment]
OK! Closing then, thanks.

You're probably one of the very first users of this app, so please let me know if you run into any issues!
